name: PR

on:
  pull_request:
    branches: [ develop ]

  push:
    branches:
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        shell: pwsh
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage" -r ./output;
          $testOutput = Get-ChildItem -Path ./output -Include *.cobertura.xml -Recurse | Select-Object Fullname -ExpandProperty FullName -First 1;
          dotnet tool install -g dotnet-reportgenerator-globaltool;
          reportgenerator -reports:$testOutput -targetdir:./output/coveragereport -reporttypes:Html;

      - name: Upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./output/coveragereport/*